# Generated by Django 3.0.6 on 2020-05-23 00:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('cgapi', '0001_initial'), ('cgapi', '0002_dummy_asks'), ('cgapi', '0003_rename_posts'), ('cgapi', '0004_create_models'), ('cgapi', '0005_django_users'), ('cgapi', '0006_user_username'), ('cgapi', '0007_posting_model'), ('cgapi', '0008_posting_count'), ('cgapi', '0009_phone_fix')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'community',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('profile_text', models.CharField(max_length=160)),
                ('member_of', models.ManyToManyField(related_name='members', to='todoapi.Community')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('password', models.CharField(default='', max_length=128, verbose_name='password')),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('username', models.CharField(default='', max_length=160, unique=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapi.User')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=256, null=True)),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'posting',
                'ordering': ['id'],
            },
        ),
    ]
