# Generated by Django 3.0.6 on 2020-06-04 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgapi', '0002_user_homes'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='home_pic',
            field=models.ImageField(default='', upload_to='cimg/'),
        ),
        migrations.AddField(
            model_name='posting',
            name='item_pic',
            field=models.ImageField(default='', upload_to='pimg/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='uimg/'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='in_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cgapi.Community'),
        ),
    ]
