# Generated by Django 3.0.6 on 2020-06-11 22:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgapi', '0003_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=160, unique=True)),
                ('profile_text', models.CharField(max_length=160)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('profile_pic', models.ImageField(default='', upload_to='uimg/')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgapi.Community')),
                ('member_of', models.ManyToManyField(related_name='members', to='cgapi.Community')),
            ],
            options={
                'db_table': 'userprofile',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='posting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cgapi.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
