# Generated by Django 3.0.6 on 2020-06-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapi', '0005_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='request',
            field=models.BooleanField(default=True),
        ),
    ]
