# Generated by Django 3.0.6 on 2020-06-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgapi', '0006_posting_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
