# Generated by Django 3.0.6 on 2020-07-24 21:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapi', '0010_posting_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posting',
            old_name='point',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='home',
            new_name='home_community',
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
