# Generated by Django 3.0.6 on 2020-07-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgapi', '0011_locations_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='home_community',
            new_name='home',
        ),
    ]
