// export const base_url = 'https://cellular-virtue-277000.uc.r.appspot.com/';
export const base_url = 'https://ace-mote-270703.wl.r.appspot.com/';
export const login_url = base_url + 'token/';
export const register_url = base_url + 'register/';
export const check_username_url = base_url + 'check-username/?username=';
export const postings_url = base_url + 'postings/';
export const email_url = base_url + 'postings/contact/';
export const users_url = base_url + 'auth/';
export const profiles_url = base_url + 'profiles/';
export const communities_url = base_url + 'communities/';
