# Generated by Django 3.0.6 on 2020-05-06 01:03

from django.db import migrations

def create_dummy_asks(apps, schema_editor):
    Ask = apps.get_model('todoapi', 'Ask')

    Ask(title='Apple').save()
    Ask(title='Milk').save()
    Ask(title='Incontinence product').save()

class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_asks)
    ]
