# Generated by Django 3.0.6 on 2020-05-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_dummy_asks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ask',
            new_name='Post',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
