# Generated by Django 3.0.6 on 2020-05-11 20:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_auto_20200508_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('profile', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapi.User'),
        ),
    ]
