# Generated by Django 3.0.6 on 2020-05-13 04:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0003_rename_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'community',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'posting',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('profile', models.CharField(max_length=160)),
                ('member_of', models.ManyToManyField(related_name='members', to='todoapi.Community')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='posting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapi.User'),
        ),
    ]
