# Generated by Django 3.0.6 on 2020-05-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0004_auto_20200512_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='member_of',
            field=models.ManyToManyField(related_name='members', to='todoapi.Community'),
        ),
    ]
