# Generated by Django 3.0.6 on 2020-05-14 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0004_auto_20200511_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('members', models.ManyToManyField(related_name='member_of', to='todoapi.User')),
            ],
            options={
                'db_table': 'community',
                'ordering': ['id'],
            },
        ),
    ]
