# Generated by Django 3.0.6 on 2020-05-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_auto_20200513_0117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posting',
        ),
        migrations.AlterModelTable(
            name='posting',
            table='posting',
        ),
    ]
