# Generated by Django 3.0.6 on 2020-05-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_django_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
