runtime: custom
env: flex
entrypoint: "python3 manage.py runserver 0.0.0.0:8080"

beta_settings:
  cloud_sql_instances: "cellular-virtue-277000:us-central1:cg-prod=tcp:5432"

runtime_config:
  python_version: 3

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto